default:
  nycdbconnection:
    driver: 'Postgres'
    host: 'localhost'
    user: 'xxx'
    password: 'xxx'
    port: 5432
    dbname: 'nycdb'

docker:
  nycdbconnection:
    host: 'host.docker.internal'

shinyapps:
  nycdbconnection:
    driver: 'Postgres'
    host: 'xxx'
    user: 'xxx'
    password: 'xxx'
    port: 5432
    dbname: 'xxx'
