default:
  nycdbconnection:
    driver: 'Postgres'
    host: 'localhost' # use 'host.docker.internal' if running locally in docker
    user: 'xxx'
    password: 'xxx'
    port: 5432
    dbname: 'nycdb'

shinyapps:
  nycdbconnection:
    driver: 'Postgres'
    host: 'xxx'
    user: 'xxx'
    password: 'xxx'
    port: 5432
    dbname: 'xxx'
